apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multus-tokenrequest
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multus-tokenrequest
subjects:
  - kind: ServiceAccount
    name: multus
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus-tokenrequest
